import {
  Black,
  BlackAlpha,
  DARKLINK,
  LightBlack,
  LightWhite,
  LINK,
  ONLINE,
  White,
  WhiteAlpha,
} from '../themes/constantColors';
import {FOLLOWING, LLightBlack, LLightWhite, Red} from './constantColors';
import {PixelRatio} from 'react-native';

export const THEMES = [
  {
    key: 'DARK',
    gradientColors: ['#85F7FE', '#91E0FA', '#A4BBF3', '#BB8FEC', '#81FFFF'],
    gradientTransparentColors: ['transparent', 'transparent'],
    container: {
      backgroundColor: Black,
      headerTextColor: White,
      shadowOpacity: PixelRatio.getPixelSizeForLayoutSize(1000)
    },
    primaryColor: White,
    primaryAlphaColor: WhiteAlpha,
    secondaryColor: LightWhite,
    secondarySColor: LLightWhite,
    //buttonRed: '#85F7FE',
    //followColor: '#85F7FE',
    //followingColor: '#85F7FE',
    //onlineColor: '#85F7FE',
    linkColor: DARKLINK,
    icons: {
      back: require('./../assets/dark/back.png'),
      close: require('./../assets/dark/close.png'),
      camera: require('./../assets/dark/camera.png'),
      delete: require('./../assets/dark/delete.png'),
      done: require('./../assets/dark/done.png'),
      send: require('./../assets/dark/send.png'),
      setting: require('./../assets/dark/settings.png'),
      options: require('./../assets/dark/options.png'),
      play: require('./../assets/dark/play.png'),
      post: require('./../assets/dark/post.png'),
      search: require('./../assets/dark/search.png'),
      comment: require('./../assets/dark/message.png'),
      unlike: require('./../assets/dark/unlike.png'),
      unmark: require('./../assets/dark/unmark.png'),
      home: require('./../assets/dark/home.png'),
      message: require('./../assets/dark/message.png'),
      activity: require('./../assets/dark/activity.png'),
      profile: require('./../assets/dark/profile.png'),
      like: require('./../assets/light/like.png'),
      mark: require('./../assets/light/mark.png'),
      selectedDone: require('./../assets/light/selectedDone.png'),
      selectedPost: require('./../assets/light/selectedPost.png'),
      selectedSearch: require('./../assets/light/selectedSearch.png'),
      selectedHome: require('./../assets/light/selectedHome.png'),
      selectedMessage: require('./../assets/light/selectedMessage.png'),
      selectedActivity: require('./../assets/light/selectedActivity.png'),
      selectedProfile: require('./../assets/light/selectedProfile.png'),
    }
  },
  {
    //key: 'rgba(138,142,150,0.31)',
    gradientColors: ['#85F7FE', '#91E0FA', '#A4BBF3', '#BB8FEC', '#81FFFF'],
    gradientTransparentColors: ['transparent', 'transparent'],
    container: {
      backgroundColor: 'rgba(18,18,19,0.08)',
      headerTextColor: Black,
      overflow: ' visible',
      padding:100,
      shadowOpacity: PixelRatio.getPixelSizeForLayoutSize(1000)

    },
    backgroundColor: '#c70e0e',
    shadowColor: 'rgb(253,243,243)',
    shadowOpacity: PixelRatio.getPixelSizeForLayoutSize(1000),


    padding: 10,

    primaryColor: Black,
    primaryAlphaColor: BlackAlpha,
    secondaryColor: 'rgb(253,243,243)',
    secondarySColor: LLightBlack,
    buttonRed: Red,
    followColor: Red,
    followingColor: FOLLOWING,
    onlineColor: ONLINE,
    linkColor: LINK,
    icons: {
      back: require('./../assets/light/back.png'),
      close: require('./../assets/light/close.png'),
      camera: require('./../assets/light/camera.png'),
      delete: require('./../assets/dark/delete.png'),
      done: require('./../assets/light/done.png'),
      send: require('./../assets/light/send.png'),
      setting: require('./../assets/light/settings.png'),
      options: require('./../assets/light/options.png'),
      play: require('./../assets/light/play.png'),
      post: require('./../assets/light/post.png'),
      search: require('./../assets/light/search.png'),
      comment: require('./../assets/light/message.png'),
      unlike: require('./../assets/light/unlike.png'),
      unmark: require('./../assets/light/unmark.png'),
      home: require('./../assets/light/home.png'),
      message: require('./../assets/light/message.png'),
      activity: require('./../assets/light/activity.png'),
      profile: require('./../assets/light/profile.png'),
      like: require('./../assets/light/like.png'),
      mark: require('./../assets/light/mark.png'),
      selectedDone: require('./../assets/light/selectedDone.png'),
      selectedPost: require('./../assets/light/selectedPost.png'),
      selectedSearch: require('./../assets/light/selectedSearch.png'),
      selectedHome: require('./../assets/light/selectedHome.png'),
      selectedMessage: require('./../assets/light/selectedMessage.png'),
      selectedActivity: require('./../assets/light/selectedActivity.png'),
      selectedProfile: require('./../assets/light/selectedProfile.png'),
    }
  },
];
